- name: copy the template file to the host
  hosts: db_servers
  vars:
    author_name: Monish
    author_email: monish.mohanpan@gmail.com
 
  tasks:
    - name: copy the file to /home/ansible
      copy:
        src: /root/ansible-docker-lab/labs/lab04/info.txt.j2
        dest: /root/ansible-docker-lablabs/lab04/t1.txt
    - name: copy the file to /home/ansible with variable substitution
      template:
        src: /root/ansible-docker-lab/labs/lab04/info.txt.j2
        dest: /root/ansible-docker-lab/t2.txt