---
# tasks file for roles/nginx-server

- name: Update and upgrade package index
  apt: 
    update_cache: yes
    upgrade: yes
- name: Install nginx server
  apt:
    name: ngnix
    state: present
    notify: Restart nginx
- name: create the homepage
  template: 
    src: templates/index.html.j2
    dest: /var/www/html/index.html
- name: copy css files
  copy: 
    src: "files/*.css"
    dest: /var/www/html/index.html
- name: start and enable nginx server
  service: nginx 
  state: started
  enabled: yes
