---

- name: Gather and save target host info
  hosts: all
  gather_facts: true
  vars:
    directory_name: facts
  tasks:
    - name: CREATE FOLDER FOR COLLLECTING FACTS
      file:
        name: "{{directory_name}}"
        state: directory
      delegate_to: localhost
      run_once: true
    
    - name: SAVE FILE IN LOCAL FILE
      copy:
        content: |
          Information about the target host:
          Hostname: {{ansible_hostname}}
          OS_kerne_version: {{ansible_kernel_version}}
          Memory:{{ansible_memory_mb.nocache}}
        dest: "{{directory_name}}/info {{ansible_hostname}}.txt"
      delegate_to: localhost