---
- name: Nginx server setup
  hosts: webservers
  become: yes

  tasks:
    - name: install nginx server
      apk:
        name: nginx
        state: present
        update_cache: yes
    - name: start nginx server
      service: 
        name: nginx
        state: started
        enabled: true